# code-god-object-6 negative: the class has exactly 30 methods at four-space indent, plus module-level and nested defs that are NOT methods, so it must NOT fire; a naive unanchored `def ` count would flag it.
def open_connection(dsn):
    return {"dsn": dsn}


def close_connection(conn):
    conn.clear()


def format_currency(cents):
    return f"${cents / 100:.2f}"


def format_percent(ratio):
    return f"{ratio * 100:.1f}%"


class ReportBuilder:
    """Builds the monthly revenue report from pre-aggregated rows."""

    def __init__(self, conn):
        self.conn = conn

    def revenue(self, month):
        return self.conn["revenue"][month]

    def orders(self, month):
        return self.conn["orders"][month]

    def refunds(self, month):
        return self.conn["refunds"][month]

    def net_revenue(self, month):
        return self.revenue(month) - self.refunds(month)

    def average_order_value(self, month):
        return self.revenue(month) / max(self.orders(month), 1)

    def refund_rate(self, month):
        return self.refunds(month) / max(self.revenue(month), 1)

    def month_over_month(self, month, previous):
        return (self.revenue(month) - self.revenue(previous)) / max(self.revenue(previous), 1)

    def top_channels(self, month, limit=5):
        return self.conn["channels"][month][:limit]

    def revenue_by_channel(self, month):
        return self.conn["by_channel"][month]

    def new_customers(self, month):
        return self.conn["new_customers"][month]

    def returning_customers(self, month):
        return self.conn["returning"][month]

    def churn(self, month):
        lost = self.conn["churned"][month]
        start = self.conn["start_of_month"][month]
        return lost / max(start, 1)

    def header(self, month):
        def label(value):
            return value.strftime("%B %Y")

        return label(month)

    def footer(self):
        def signature():
            return "generated by ReportBuilder"

        return signature()

    def total_row(self, month):
        return {
            "revenue": format_currency(self.revenue(month)),
            "orders": self.orders(month),
            "net": format_currency(self.net_revenue(month)),
        }

    def summary_rows(self, month):
        return [self.total_row(month), {"refund_rate": format_percent(self.refund_rate(month))}]

    def channel_rows(self, month):
        return [{"channel": c, "revenue": format_currency(v)} for c, v in self.revenue_by_channel(month).items()]

    def customer_rows(self, month):
        return [{"new": self.new_customers(month), "returning": self.returning_customers(month)}]

    def churn_row(self, month):
        return {"churn": format_percent(self.churn(month))}

    def sections(self, month):
        return [self.header(month), self.summary_rows(month), self.channel_rows(month)]

    def render(self, month):
        lines = [self.header(month)]
        for section in self.sections(month):
            lines.extend(str(row) for row in section)
        return "\n".join(lines)

    def export_csv(self, month):
        return self.render(month).replace("\n", "\r\n")

    def export_json(self, month):
        return {"month": month.isoformat(), "rows": self.summary_rows(month)}

    def export_markdown(self, month):
        return "\n".join(f"| {row} |" for row in self.summary_rows(month))

    def cache_key(self, month):
        return f"report:{month.isoformat()}"

    def is_empty(self, month):
        return self.orders(month) == 0

    def warnings(self, month):
        return [] if self.orders(month) else ["no orders in period"]

    def export_pdf(self, month):
        return self.render(month).encode("latin-1")

    def cache_ttl_seconds(self):
        return 3600
